2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Configure stats pid to 26390
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Loading settings from /Users/xaviermootoo/.config/wandb/settings
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Loading settings from /Users/xaviermootoo/Documents/VScode/ssl-seizure-detection/notebooks/wandb/settings
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_init.py:_log_setup():528] Logging user logs to /Users/xaviermootoo/Documents/VScode/ssl-seizure-detection/notebooks/wandb/run-20231105_164434-4nvnjhrk/logs/debug.log
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/xaviermootoo/Documents/VScode/ssl-seizure-detection/notebooks/wandb/run-20231105_164434-4nvnjhrk/logs/debug-internal.log
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_init.py:init():568] calling init triggers
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'num_node_features': 9, 'num_edge_features': 3, 'hidden_channels': [64, 32, 64, 128, 256]}
2023-11-05 16:44:34,731 INFO    MainThread:26390 [wandb_init.py:init():593] re-initializing run, found existing run on stack: wdpp1tl7
2023-11-05 16:44:34,734 INFO    MainThread:26390 [wandb_run.py:_finish():1934] finishing run xmootoo/ssl-seizure-detection/wdpp1tl7
2023-11-05 16:44:34,734 INFO    MainThread:26390 [jupyter.py:save_history():445] not saving jupyter history
2023-11-05 16:44:34,734 INFO    MainThread:26390 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 16:44:34,734 INFO    MainThread:26390 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-11-05 16:44:34,735 INFO    MainThread:26390 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-11-05 16:44:34,735 INFO    MainThread:26390 [wandb_run.py:_restore():2151] restore
2023-11-05 16:44:34,735 INFO    MainThread:26390 [wandb_run.py:_restore():2157] restore done
2023-11-05 16:44:38,932 INFO    MainThread:26390 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-11-05 16:44:38,933 INFO    MainThread:26390 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-11-05 16:44:38,942 INFO    MainThread:26390 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-11-05 16:44:39,136 INFO    MainThread:26390 [wandb_init.py:init():618] starting backend
2023-11-05 16:44:39,136 INFO    MainThread:26390 [wandb_init.py:init():622] setting up manager
2023-11-05 16:44:39,138 INFO    MainThread:26390 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-05 16:44:39,139 INFO    MainThread:26390 [wandb_init.py:init():628] backend started and connected
2023-11-05 16:44:39,154 INFO    MainThread:26390 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-11-05 16:44:39,154 INFO    MainThread:26390 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-05 16:44:39,154 INFO    MainThread:26390 [wandb_init.py:init():720] updated telemetry
2023-11-05 16:44:39,281 INFO    MainThread:26390 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-11-05 16:44:40,973 INFO    MainThread:26390 [wandb_run.py:_on_init():2220] communicating current version
2023-11-05 16:44:41,095 INFO    MainThread:26390 [wandb_run.py:_on_init():2229] got version response 
2023-11-05 16:44:41,095 INFO    MainThread:26390 [wandb_init.py:init():804] starting run threads in backend
2023-11-05 16:44:41,239 WARNING MainThread:26390 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 815, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/xaviermootoo/opt/anaconda3/envs/torch2_mps/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
